apiVersion: apps/v1
kind: Deployment
metadata:
  name: omkekfgh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omkekfgh
  template:
    metadata:
      labels:
        app: omkekfgh
    spec:
      containers:
      - image: okteto.dev/omkekfgh:latest
        name: omkekfgh
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "3f4acd7e-a954-433f-8006-3f3c22b3ca10"
        - name: Vless_Path
          value: "/vle"
        - name: Vmess_UUID
          value: "3f4acd7e-a954-433f-8006-3f3c22b3ca10"
        - name: Vmess_Path
          value: "/vme"
        - name: Share_Path
          value: "/v2link"
